Edit Test Case
thang1160/starter pull request #1
Opened 2022-11-15 13:53 UTC by duyhl512

2022-11-15 14:01 UTC, duyhl512 commented
Add

2022-11-15 14:13 UTC, duyhl512 commented
Re - moddified TestCase Handler

2022-11-15 14:25 UTC, thang1160 requested changes

2022-11-15 14:25 UTC, thang1160 commented on src/main/java/com/example/starter/dao/TestPlanDAO.java
> +            ps = conn.prepareStatement("exec [GetTestPlansByProjectId] ?;");
Thiếu file sql của GetTestPlansByProjectId

2022-11-15 14:25 UTC, thang1160 commented on src/main/java/com/example/starter/dao/TestPlanDAO.java
> +        }
chưa đóng connection và PreparedStatement

2022-11-15 14:25 UTC, thang1160 commented on src/main/java/com/example/starter/dto/TestCase.java
> +    private Integer createOn;
Sao cái này lại là Integer nhỉ

2022-11-15 14:25 UTC, thang1160 commented on src/main/java/com/example/starter/dto/TestCase.java
> -        this.updatedBy = userId;
statusId = 1, deleted = false và updatedBy = userId là default value đã chốt trong cuộc họp chủ nhật rồi

2022-11-15 14:25 UTC, thang1160 commented on src/main/java/com/example/starter/handler/TestCaseHandler.java
> +                Boolean isDeleted = json.getBoolean("is-deleted");
Tương tự những params này không cần thiết lấy ra, em check lại swagger trước khi sửa lại

2022-11-16 05:22 UTC, duyhl512 commented
Em đã chỉnh sửa lại các file trên, anh xem xét lại giúp e

2022-11-16 09:33 UTC, thang1160 approved these changes

2022-11-16 09:44 UTC, merged